name:                fast-etl-launcher
version:             0.1.0.0
github:              "devcdcc/fast-etl"
license:             MIT
author:              "Carlos Daniel Cañon Carrero"
maintainer:          "devcdcc@gmail.com"
copyright:           "2021 Carlos Daniel Cañon Carrero"
#extra-source-files:
#- ../../core/dag-validator-lib/src/**/*.rs
#- ../../core/dag-validator-lib/Cargo.toml

library:
  source-dirs: src
  extra-libraries:     gcc_eh, pthread

dependencies:
  - base >= 4 && < 5
  - swagger2

executables:
  dag-launcher:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
    extra-libraries:     gcc_eh, pthread
